### PR TITLE
Custom icons for checkbox component

### LINKED ISSUE #3298: Checkbox: Allow custom icons
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for checkbox component

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Magiczne**
Resolves #3298

### CODE REVIEW

**Comment by Magiczne** [comment]
@tugcekucukoglu @bahadirsofuoglu looks like workflow is broken

**Comment by bahadirsofuoglu** [comment]
Hi, You should use only tags. Not URL. I know this is complicated. I will search for alternative solutions. Thank you for your contributions.

**Comment by Magiczne** [comment]
Oh, thanks a lot. Didn't see that is an url, just copied it from old PR

**Comment by tugcekucukoglu** [comment]
We decided to use icon template instead of icon property to support svg, png etc. Under these circumstances, we will not be able to accept these PRs.

**Comment by cagatayuncu** [comment]
Hello Everyone , 
I want to replace the checkbox with star and fill-star icons in the case of a datatable (selectionMode="multiple"), can you support me with an example usage? 

image


@tugcekucukoglu 
@Magiczne 
@bahadirsofuoglu

**Pull request closed without merging**
