### PR TITLE
fix(tree): checkbox partialChecked not correct when filtering

### PR DESCRIPTION
**Pull request by EmreAka**
Fixes https://github.com/primefaces/primevue/issues/6928

The issue states that the defect is present in version 3, but it also presents in version 4.

**Tree Node**
- Added a new prop. `unfilteredNode`: The original node data before any filtering.
- Added a new computed value. `currentNode`: Returns unfilteredNode if available; otherwise, returns node.
- Added a new method. `getUnfilteredNode(node)`: Retrieves the unfiltered version of a node. Only works when its filtered and selection mode is set checkbox.

**Tree**
- Added `getUnfilteredNode` method to retrieve nodes without filtering when in checkbox selection mode. Only works when its filtered and selection mode is set checkbox.

### CODE REVIEW

**Comment by arneyjfs** [comment]
@tugcekucukoglu marked this as a duplicate of https://github.com/primefaces/primevue/issues/6940 although it seems slightly different, but perhaps it is the fix that is related not the exact symptom? @EmreAka do you know if this PR fixes both issues or if it would be a simple addition to include it?

**Comment by EmreAka** [comment]
@arneyjfs No, that does not resolve the issue as they are unrelated.

**Comment by tugcekucukoglu** [comment]
We reviewed the PR and the filter works correctly but the checkbox selection seems broken. So we can't accept it. But we are open to new solutions.

**Comment by EmreAka** [comment]
Thanks for the feedback. I'll try to identify and solve the problem.

**Pull request closed without merging**
