### PR TITLE
Update package.json for menuitem

### PR DESCRIPTION
**Pull request by meveno**
Simple bugfix to correct vite dev dependency error :

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "primevue/menuitem". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "primevue/menuitem". The package may have incorrect main/module/exports specified in its package.json.

###Defect Fixes
When submitting a PR, please also create an issue documenting the error.

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.

### CODE REVIEW

**Comment by tugcekucukoglu** [comment]
When submitting a PR, please also create an issue documenting the error.

**Comment by tugcekucukoglu** [comment]
Closing due to inactivity.

**Comment by omirete** [comment]
Hi! What is missing for this to be merged? There exists an issue ( #3498 ) which would be resolved by this PR.

**Comment by colinbes** [comment]
Any joy on this? I have hit the same issue but with later primevue 3.29.2

**Pull request closed without merging**
