### PR TITLE
Rating with decimals

### PR DESCRIPTION
**Pull request by Rakasch**
add support for decimal values to rating component

image

### CODE REVIEW

**Comment by cagataycivici** [comment]
Thank you, this is something that we prefer to do it by ourselves. Still we'll use your PR as a valuable feedback. Thank you.

**Comment by slavco86** [comment]
@cagataycivici Any news on this feature being actually worked on?

**Comment by BenJackGill** [comment]
Can this be added? The other PR was done but got rejected as a duplicate of this one... which hasn't had any movement since 2021...

**Comment by slavco86** [comment]
Agree - this really needs to be implemented. It's very disappointing for this component not to support half star rating

**Comment by flow96** [comment]
Why has this been closed and not merged?

**Pull request closed without merging**
