### PR TITLE
Fix Inplace focus trap

### LINKED ISSUE #6218: Inplace: Autofocus not working for content slot
### Describe the bug

The `Inplace` Component currently doesn't support `autofocus` attribute on e.g. `InputText` component. This was already fixed somewhere in version 3 of PrimeVue but got broken again in PrimeVue 4.0.0.

There is also an example in the showroom where the `autofocus` is used but not working. See here: 
https://primevue.org/inplace/#input

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-xtudnc?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Add `Inplace` component
2. Add `InputText` component with `autofocus` attribute to `content` slot
3. Add a simple `display` slot
4. Click on display
5. InputText is not focused automatically

### Expected behavior

The input should be focused automatically when the `autofocus` attribute is set

### PR DESCRIPTION
**Pull request by lasficw**
### Defect Fixes
This fixes #6218

### CODE REVIEW

**Comment by ZiadJ** [comment]
Would probably be better to make `focusTrap` an optional prop and then fix `autofocus` in the `InputText `instead, which should be working regardless in any circumstance.

**Comment by ZiadJ** [comment]
Probably also worth noting that the [React version](https://primereact.org/inplace/) works just fine without limiting the focus scope

**Comment by tugcekucukoglu** [comment]
Using `content` slot, you can add a wrapper and `focustrap` directive for your demo.

**Comment by daisnkzy** [comment]
> Using `content` slot, you can add a wrapper and `focustrap` directive for your demo.

I don't know how to do it for what you say, can you give me an example?

**Pull request closed without merging**
