### PR TITLE
Allow users to specify the different icons to use, and fix documentation around classes used.

### LINKED ISSUE #3299: TriStateCheckbox: Allow custom icons
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for tri- state checkbox component

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ancient-Dragon**
### Feature Requests
Resolves #3299

### CODE REVIEW

**Comment by Ancient-Dragon** [comment]
@tugcekucukoglu please can you review this when you get a change?

**Comment by Ancient-Dragon** [comment]
Thanks!

**Comment by Ancient-Dragon** [comment]
@tugcekucukoglu Any chance of this being in the next release? We'd really like to use this functionality in our next release,

**Comment by tugcekucukoglu** [comment]
We decided to use icon template instead of icon property to support svg, png etc. Under these circumstances, we will not be able to accept these PRs.

**Pull request closed without merging**
