### PR TITLE
Fix Multiselect: Menu closes on select #4861

### PR DESCRIPTION
**Pull request by MaXal**
###Defect Fixes
Fix for #4861

### CODE REVIEW

**Comment by tugcekucukoglu** [comment]
Cannot replicate issue with the latest version. How can replicate the issue?

**Comment by MaXal** [comment]
@tugcekucukoglu Thank you for looking into the PR. The issue is still reproducible with V4: https://stackblitz.com/edit/ivkrzp?file=src%2FApp.vue

**Comment by tugcekucukoglu** [comment]
You could try to add a theme and if you prefer unstyled mode, `unstyled` prop should be added to the component.

**Comment by MaXal** [comment]
@tugcekucukoglu I've added the theme, and the behavior is still the same, and the fix still fixes the issue with closing dropdown.

I also tried unstyled and the behavior is the same. As you can see in the PR, the fix has nothing to do with the themes since the issue is with the `isOutsideClicked` method.

**Pull request closed without merging**
