### PR TITLE
Tooltip: autoHide

### PR DESCRIPTION
**Pull request by MiAnMy**
#3568

Add autoHide feature, with documentation

### CODE REVIEW

**Comment by mertsincan** [comment]
Hi @MiAnMy,

Thanks a lot for your contribution! But, this PR is outdated! Could you please update it? Then, I'll review it asap.

Best Regards,

**Comment by tugcekucukoglu** [comment]
Thanks a lot for your contribution! But, this PR is outdated! Could you please update it? Then, I'll review it asap.

**Comment by MiAnMy** [comment]
Updated

**Comment by tugcekucukoglu** [comment]
Thanks for the updates!

I've tried the PR that you have sent. https://stackblitz.com/edit/ywgkvp?file=src%2FApp.vue,src%2Fmain.js%3AL13,src%2FBaseTooltip.js

It seems autoHide demo does not work as expected.

**Comment by MiAnMy** [comment]
@tugcekucukoglu 

The given link does not fully contain my changes. If you remove the "pointer-events" attribute, it should work.

https://stackblitz.com/edit/ywgkvp-5eekri?file=src%2FBaseTooltip.js

**Pull request merged**
