### PR TITLE
fix issue #5335 and #5329

### PR DESCRIPTION
**Pull request by franmc01**
Fix https://github.com/primefaces/primevue/issues/5335
Fix https://github.com/primefaces/primevue/issues/5329

### CODE REVIEW

**Comment by franmc01** [comment]
Hello! It's Francisco once again. This time I'm building upon my initial contribution by adding another fix, this time at the library level. I am pleased to present further enhancements to the InputOtp component that address specific issues and improve the overall quality of the codebase:

### Numeric Keypad Input Handling Correction
**Resolved Issue [#5335](https://github.com/primefaces/primevue/issues/5335):**
**Resolved Issue [#5329](https://github.com/primefaces/primevue/issues/5329):**

Previously, the `integerOnly` property did not allow the use of the numeric keypad.

**Implemented Solution:**
The `onKeyDown` method has been updated to utilize `event.key`, ensuring compatibility with numeric keypads and improving consistency for users.

### Paste Event Enhancement
The component permitted the pasting of non-numeric content, even when `integerOnly` was enabled.

**Implemented Solution:**
The `onPaste` event has been optimized to filter and accept only numeric characters in `integerOnly` mode.

### Additional Improvement: Adoption of `event.key`
In an effort to refine the codebase, we have phased out the deprecated `event.keyCode` in favor of `event.key`. This not only adheres to modern recommendations for keyboard event compatibility and standardization but also enhances the code's readability and maintainability, setting it up for future extensions and modifications.

### Testing and Feedback
Detailed manual testing has been conducted, and I am open to feedback to ensure these changes meet the project standards and user expectations.

I appreciate the review of this PR and the opportunity to contribute meaningful improvements to the PrimeVue project.

Best regards,
Francisco

**Comment by franmc01** [comment]
Hey @cagataycivici and @tugcekucukoglu! What do you think about this? =)

**Comment by melloware** [comment]
@franmc01 if you change your comment to the following:

Fix https://github.com/primefaces/primevue/issues/5335
Fix https://github.com/primefaces/primevue/issues/5329

It will link both those tickets to this PR.

**Comment by franmc01** [comment]
@melloware All comments or just initial? In my second comment I had already linked them

**Comment by melloware** [comment]
Yes in your first comment. Also you had...

```
Resolved Issue https://github.com/primefaces/primevue/issues/5335:
Resolved Issue https://github.com/primefaces/primevue/issues/5329:
```

It needs to be...

```
Fix https://github.com/primefaces/primevue/issues/5335
Fix https://github.com/primefaces/primevue/issues/5329
```

Exactly for GitHub to pick it up.

**Comment by franmc01** [comment]
@melloware ready =)

**Comment by tugcekucukoglu** [comment]
It seems to have been resolved by other PRs. Closing it due to conflicts.

Thanks for your time and effort.

**Pull request closed without merging**
