### PR TITLE
Menu: set the initial focus item of the menu when `popup` is true.

### LINKED ISSUE #3210: Menu: Make initial focus id configurable on popup menus
### Describe the feature you would like to see added

Make initial index of focus in Menu component configurable. In 3.18 there was a change that focuses the first menu item in a popup list. This is something i would like to disable as it does not fit my usage of the component.

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

Add prop that makes this configurable.

### Describe alternatives you have considered

Currently i am listening to the "show"-event and edit focusedOptionIndex directly from component parent. But I feel this should be configurable in the component.

### Additional context

Screenshot from 2022-11-05 10-26-19
Top item is in focus and highlighted.

### PR DESCRIPTION
**Pull request by g1eny0ung**
Close #3210.

This PR is a successor of #3211. Since it is outdated and I also need this prop in my code, so I've updated the code to suit the latest version.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Hey @tugcekucukoglu, would you mind taking a look at this when you have some free time?

**Comment by tugcekucukoglu** [comment]
This affects all menu components and for now, there is no plan to add a new `initialFocus ` property.

**Comment by g1eny0ung** [comment]
@tugcekucukoglu But if I want to represent the active status of a menu item, what should I do now?

**Comment by emilsgulbis** [comment]
@g1eny0ung make first item something like

```{ class: 'hidden' }```

**Pull request closed without merging**
