### PR TITLE
fix: table paginator, which fire double event from jumpToPageInput

### LINKED ISSUE #3409: DataTable/Paginator: Double event fire in JumpToPageInput
### Describe the bug

1. Go into reproduction sandbox and open sandbox console
2. Enter "3" in the JumpToPage input then press enter
3. Then click oustide the input
4. Look at the console - there are two fired events.

### Reproducer

https://codesandbox.io/s/funny-sun-jjhbg8

### PrimeVue version

3.21

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

When page does not change the input should not trigger event.

### PR DESCRIPTION
**Pull request by volvachev**
### Defect Fixes
Fixes #3409

### CODE REVIEW

**Comment by tugcekucukoglu** [comment]
Thanks for the solution!

Unfortunately, we do not prefer to use optional chaining. If you're still interested please update your PR.

**Comment by volvachev** [comment]
Hi, @tugcekucukoglu I updated the pr

**Comment by volvachev** [comment]
Hi, @cagataycivici why is it closed?

**Comment by tugcekucukoglu** [comment]
We've updated the master branch. You could reopen this PR with an update.

Thanks!

**Pull request closed without merging**
