### PR TITLE
ConfirmPopup: acceptClass and rejectClass is not working on unstyled …

### PR DESCRIPTION
**Pull request by sescandell**
…mode

###Defect Fixes
Same as https://github.com/primefaces/primevue/issues/4412  but for ConfirmPopup
(Fix using the same solution as ConfirmDialog https://github.com/primefaces/primevue/commit/26c9df3424fd19404f449ca703ff7c695801624b)

### CODE REVIEW

**Comment by tugcekucukoglu** [comment]
https://github.com/primefaces/primevue/issues/4412

The issue is already resolved when you send the PR. So I'm closing it.

**Comment by sescandell** [comment]
@tugcekucukoglu no... the issue resolved for the COnfirmDialog.
Here, I am resolving it for ConfirmPopup... it is the SAME issue on ANOTHER component

**Comment by sescandell** [comment]
@tugcekucukoglu could we please re-open this PR?

**Comment by tugcekucukoglu** [comment]
Did you try to use the latest version? Because it seems it was fixed for 3.34.1. https://github.com/primefaces/primevue/issues/4412

**Comment by tugcekucukoglu** [comment]
Sorry, it is my mistake. 

You need to open an issue before submitting a PR, and if you open an issue and fix the conflicts we will review it.

**Comment by sescandell** [comment]
See #4507

**Pull request closed without merging**
