### PR TITLE
Fixed #3205 - Calendar: emit Event on invalid input

### LINKED ISSUE #3205: Calendar: emit Event on invalid input
### Describe the feature you would like to see added

I would like to react to user input on the calendar field if invalid.

Currently, if the field is invalid, nothing happens, see [this line in Calendar.vue](https://github.com/primefaces/primevue/blob/master/src/components/calendar/Calendar.vue#L2570).

### Is your feature request related to a problem?

The problem is that Calendar parses the manually typed value completely internally, with no way for me to react to it.

### Describe the solution you'd like

I would like to see an event, called let's say `InvalidInput`, emitted on the aforementioned [line in the catch block](https://github.com/primefaces/primevue/blob/master/src/components/calendar/Calendar.vue#L2570).

It would be highly helpful if the event was bundled with the data that was invalid, i.e. [event.target.value](https://github.com/primefaces/primevue/blob/master/src/components/calendar/Calendar.vue#L2563).

### Describe alternatives you have considered

Emitting the event seems the most Vue-like solution to me.

### Additional context

Imho, this shouldn't be that difficult to implement. Feel free to correct me :D

### PR DESCRIPTION
**Pull request by AurumTheEnd**
Fixed #3205, as was instructed.

Was inspired by db46ee81af43312eaa33229def0ca825879f1138, which added another Calendar event.

Hopefully this can hit production soon :pray:

### CODE REVIEW

**Comment by AurumTheEnd** [comment]
Unfortunately, the failing unit tests are not in any files that I have edited.

**Comment by AurumTheEnd** [comment]
Tried to re-trigger the pipeline with a force-push (of the same commit, don't worry), but it needs "a maintainer to approve" again. :/

**Comment by AurumTheEnd** [comment]
Mergable now!

**Comment by tugcekucukoglu** [comment]
valid or not the input event fires.

Thanks for your contribution!

**Comment by AurumTheEnd** [comment]
@tugcekucukoglu You closed this MR, did not merge it, and yet you finished the #3205 issue as completed!?

Did I implement it wrong? :(

**Pull request closed without merging**
