### PR TITLE
feat: add appendTo support for tooltip directive resolves #4053

### LINKED ISSUE #4053: Tooltip: Add appendTo option
### Describe the feature you would like to see added

The current implementation appends the tooltip to document.body. 

image

It would be nice to have the option to have the option to attach it to some other element in the DOM. 

### Is your feature request related to a problem?

Due to the setup of some of our projects, custom styling from PrimeVue themes are not scoped on the the document.body but on some element within it. It is not possible to scope it at the document.body due to the setup, making it impossible to add styling to the tooltip. This is also the case when using the class property in the directive options. 

### Describe the solution you'd like

I would like to add an (optional) parameter to the tooltip properties: appendTo. If the option is not set, the tooltip is appended to document.body. Otherwise, the tooltip is appended to the provided html element. 

Example:
image

### Describe alternatives you have considered

The alternative is using something like OverlayPanel and somehow toggling it on hover, but I think it is preferable to not have add custom logic like that for each time we need to use a tooltip (which is often)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by indy-sendhar**
Implemented support for appendTo as described in this issue https://github.com/primefaces/primevue/issues/4053

### CODE REVIEW

**Comment by antoinezanardi** [comment]
I'm looking forward for this feature ! Thanks for your PR !

**Comment by tugcekucukoglu** [comment]
We suggest using OverlayPanel and not planning to add new options like `appendTo`.

Thanks for your time and work.

**Comment by indy-sendhar** [comment]
Thanks for reviewing my PR and suggesting OverlayPanel. I'm curious about the decision against the appendTo option for tooltips. The feature is sought after in the community, mainly because OverlayPanel doesn’t support hover like tooltips do. The appendTo would really help position tooltips better in complex layouts.

Could we reconsider adding this to tooltips? It seems like it would make them more versatile without affecting existing functionality.

Appreciate your time and looking forward to your input.

**Comment by sohaha** [comment]
@tugcekucukoglu Popover doesn't support hover, and tooltips inserted directly into the body have a hierarchy problem and must be manually zindex, so why not consider this scenario?

**Pull request closed without merging**
