### PR TITLE
Add custom icons support for the TabView component

### LINKED ISSUE #3185: TabView: Allow custom icons
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for tabview component

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Magiczne**
Resolves #3185

### CODE REVIEW

**Comment by Magiczne** [comment]
I still stick to my arguments from the #3186 - doing it in a separate props generates correct html structure, without creating too much noise.

**Comment by Magiczne** [comment]
@tugcekucukoglu @bahadirsofuoglu @cagataycivici

I've moved all my previous PRs with custom icons support. I would like to go into more advanced components like DataTable and TreeTable, since they are probably the most wanted ones, but they require some of the existing ones to be reviewed and hopefully merged.

When can I expect some feedback?

**Comment by bahadirsofuoglu** [comment]
Hi,
First of all, thank you for all the updates. We review all PR's with @cagataycivici. We want to merge soon. If there is a problem, we share it as a comment. We will make changes to the datatable (3.22.0 or next). It would be better to start after that. You can also write me on discord whenever you want. Your support is important to us.

**Comment by Magiczne** [comment]
Great, thanks! That's good then, DataTable should wait definitely if there are planned changes for it. Probably in the meantime when something is accepted I'll stick to other components mentioned in the original issue (#2979) as there are some like image and galleria that I personally haven't used yet, but probably will come handy for someone.

**Comment by bahadirsofuoglu** [comment]
You can take a break for a while. Because we need to make some decisions about the unstyled mode. You can check it on the [roadmap](https://www.primefaces.org/primevue/roadmap). I'll let you know after the decisions we make there. Thank you for your contribution.

**Comment by Tmktahu** [comment]
I looked at the roadmap... The unstyled mode seems to be slated for completion in Q2. Does that mean these PRs to allow for custom icons won't be merged until then?

I'm the middle of a process to shift from Vuetify to PrimeVue and was hoping I'd be able to customize icons on a lot of these components sooner rather than later. If that feature isn't going to be added for several months, then is there a suggest temporary workaround I could use to get better control over this icon situtation?

**Comment by Magiczne** [comment]
@Tmktahu in the meantime in projects when I'm using PrimeVue - just add CSS `content` with base-64 encoded icon. It's not the best, as the color is not fully customizable, but it works.

**Comment by Tmktahu** [comment]
@Magiczne thanks for the suggestion.

Since I manually import and register each PrimeVue component individually, I was able to make a local copy of the components I need custom icons in and then import and register those for now instead of the ones from the PrimeVue package. That way I can use the code in the PRs for the functionality until it's merged.

Hopefully they don't wait too long to merge these. Thank you so much for the work you put in to add this custom icon stuff. It was the only major downside for my project.

**Comment by tugcekucukoglu** [comment]
We decided to use icon template instead of icon property to support svg, png etc. Under these circumstances, we will not be able to accept these PRs.

**Pull request closed without merging**
