### PR TITLE
Custom icons support for TriStateCheckbox component

### LINKED ISSUE #3299: TriStateCheckbox: Allow custom icons
### Describe the feature you would like to see added

Extracted from https://github.com/primefaces/primevue/issues/2979 - adding custom icons support for tri- state checkbox component

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Magiczne**
Resolved #3299

### CODE REVIEW

**Comment by Magiczne** [comment]
@tugcekucukoglu the pipeline seems to be broken, as I've mentioned issue in the content and it is linked, but it's not working as intended.

**Comment by bahadirsofuoglu** [comment]
You need to put a space at the end of the link you added. It's a problem with the resource we use.

**Comment by Magiczne** [comment]
@bahadirsofuoglu Thanks!

**Comment by Magiczne** [comment]
@ig-onoffice-de that's probably not a scope of this and issue related to it, as I was only making existing icons available for customization. Probably you need to request a feature

**Pull request closed without merging**
