### PR TITLE
fix: Datatable multisortField - Fix undefined values sorting

### PR DESCRIPTION
**Pull request by MalikBen**
Fixes https://github.com/primefaces/primevue/issues/4555

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.

### CODE REVIEW

**Comment by mertsincan** [comment]
Thanks a lot for your contribution! @melloware Have you done any work on this in PrimeReact? If I remember correctly, you added something.

**Comment by melloware** [comment]
@mertsincan yes this all works in Primereact and I broke it out into a re-usable static utility in PrimeReact so we can use it every where we sorted and it handles locales and whether you want to sort like Excel with NULLS at top or bottom.

https://github.com/primefaces/primereact/blob/75e535833ab33f971ac66c7712134914415525c5/components/lib/utils/ObjectUtils.js#L377-L401

**Comment by melloware** [comment]
@FlipWarthog you know the PrimeVue base a little better than I do but maybe we can port the PrimeReact sorting stuff here to Primevue?

**Comment by FlipWarthog** [comment]
@melloware Sure, lemme digest what you did on the React side and see how it would fit here

**Comment by mertsincan** [comment]
@MalikBen Thanks a lot for your contribution! I think a fix like in PrimeReact might be better. So, closed.

Thanks again,
Best Regards,

**Pull request closed without merging**
