### PR TITLE
Fix #4394 - DataTable VirtualScroller: resizableColumns broken

### LINKED ISSUE #4394: DataTable VirtualScroller: resizableColumns broken
### Describe the bug

"resizableColumns" does not work anymore in a scrollable Datatable with a virtualscroller.
You can drag the column width, but the column resets as soon as you release the mouse button.

Did work with version 3.29.2, 
broken since version 3.30.0

### Reproducer

https://stackblitz.com/edit/xq17ml?file=src%2FApp.vue,src%2Fservice%2FProductService.js

### PrimeVue version

3.34.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

see Reproducer
try to change the column width

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by FlipWarthog**
Fix #4394 - DataTable VirtualScroller: resizableColumns broken

### CODE REVIEW

**Comment by melloware** [comment]
Does React have the same bug?

**Comment by FlipWarthog** [comment]
I haven't checked yet but I'll put in an Issue/PR if it does

**Comment by FlipWarthog** [comment]
@melloware issue doesn't look like it exists in PrimeReact: https://stackblitz.com/edit/react-6qw9ud?file=src%2FApp.js

**Comment by melloware** [comment]
Thanks for checking.

**Review by tugcekucukoglu — APPROVED** [review]

**Pull request merged**
