### PR TITLE
fix: #5903

### LINKED ISSUE #5903: No intellisense for props, slots etc. with v4
### Describe the bug

In v4, it seems like some types are not defined correctly as I'm getting no Intellisense for props, slots etc.

I see that you used to extend `ClassComponent` before v4
```typescript
declare class Button extends ClassComponent<ButtonProps, ButtonSlots, ButtonEmits> {}
```
Now in v4 you use `DefineComponent`
```typescript
declare const Button: DefineComponent<ButtonProps, ButtonSlots, ButtonEmits>;
```
It seems like something is still missing somewhere in the type parameter chain.

Intellisense in v3
image
Intellisense in v4
image

### Reproducer

[StackBlitz](https://stackblitz.com/~/github.com/Sector6759/primevue4)

**Edit:** this reproducer now shows the desired behavior because I updated it according to my [comment](https://github.com/primefaces/primevue/issues/5903#issuecomment-2241709437).

### PrimeVue version

4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by 2234839**
###Defect Fixes
#5903

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.

### CODE REVIEW

**Comment by Eirmas** [comment]
I have tested this fix locally, and it works for all props, slots and emits!

I would suggest renaming `GlobalComponentConstructor` to something else as it's being being used outside the scope of `GlobalComponents` in this case.

**Comment by 2234839** [comment]
@Eirmas You're right. I made some brief changes, but I didn't test them enough

**Comment by Eirmas** [comment]
@2234839 I think this looks good! If you remove `package-lock.json` that was generated from running with npm instead of pnpm, then I think this PR might have a big chance of getting merged faster :)

**Comment by 2234839** [comment]
@Eirmas  It was my oversight and the file has been removed

**Comment by Eirmas** [comment]
@tugcekucukoglu Would you like to look into this PR?

**Comment by mertsincan** [comment]
@2234839, Thanks a lot for your contribution! Could you please resolve conflicts? Then, I'll merge asap.

**Comment by 2234839** [comment]
@mertsincan I handled a few conflicts, as well as new component type changes

**Comment by mertsincan** [comment]
Perfect! Thanks a lot, @2234839 ;)

**Pull request merged**
