### PR TITLE
add toggle all label

### PR DESCRIPTION
**Pull request by karlfock**
The checkbox for selecting or unselecting all labels can only be changed by slots, adding this prop will make it easier.

Here is a related issue:
https://github.com/primefaces/primevue/issues/4501

This is how it will look:

image

Based on this:

``` <MultiSelect toggle-all-label="Select all" .../>```

### CODE REVIEW

**Comment by karlfock** [comment]
@mertsincan just updated PR since there was a new version of primevue (3.36.0).

**Comment by tugcekucukoglu** [comment]
toggleAllLabel should be a dynamic text according to selection and deselection states. In terms of DX, there will be people who do not want to see only 'Select all' text.

Thank you for your contribution.

**Comment by selemondev** [comment]
> toggleAllLabel should be a dynamic text according to selection and deselection states. In terms of DX, there will be people who do not want to see only 'Select all' text.
> 
> Thank you for your contribution.

Hey @tugcekucukoglu , any idea of how I can achieve this?

**Comment by reqwire** [comment]
is this possible yet? @tugcekucukoglu

**Comment by selemondev** [comment]
> is this possible yet? @tugcekucukoglu

I found a solution using pseudo-selectors. Check out the code below:

**Component **

`<MultiSelect v-model="selectSolutions" :options="[]" optionLabel="name" optionValue="id"
      placeholder="Select" />`

**Pseudo selector**

`.p-multiselect-panel {
    &::after {
      content: 'Toggle All';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 3rem;
      display: flex;
      align-items: center;
    }
 }`

**Here is the full scss code with the pseudo selector**: 


`.p-multiselect {
  outline: none;
  box-shadow: none;
  border: $input-outline;
  border-radius: $border-radius-sm;
  padding-right: 8px;
  width: 100%;

  .p-multiselect-label-container {
    .p-multiselect-label {
      font-size: $input-font-size;
      padding: 7px 12px;
      box-shadow: none;
      width: 100%;
    }
  }

  .p-multiselect-trigger {
    width: 18px;
    height: 18px;
    font-size: $input-font-size;
    margin-top: auto;
    margin-bottom: auto;
  }

  &:focus,
  &:hover {
    border: $input-outline;
    cursor: pointer;
  }

  &::placeholder {
    color: #aaa;
  }

  &:disabled,
  &.p-disabled {
    background-color: #f4f4f4;
    color: #aaa;
  }

  &.error {
    border: $input-error-outline;
  }
}

.p-multiselect-panel {
  .p-multiselect-header {
    position: relative;
    padding: 0 16px;
    margin: 4px 0;
    font-size: $input-font-size;
    border-radius: $border-radius-sm;

    &::after {
      content: 'Toggle All';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 3rem;
      display: flex;
      align-items: center;
    }
  }

  .p-multiselect-items {
    padding: 6px;

    .p-multiselect-item {
      padding: 0 16px;
      margin: 4px 0;
      font-size: $input-font-size;
      border-radius: $border-radius-sm;

      &.p-highlight,
      &[data-p-highlight='true'] {
        background-color: #4263eb;
        color: #fff;

        &.p-focus {
          background-color: #4263eb;
          color: #fff;
        }

        .p-checkbox {
          .p-checkbox-box {
            background-color: #fff;

            .p-checkbox-icon {
              color: #4263eb;
            }
          }
        }
      }

      &.p-focus {
        background-color: #4263eb1a;
      }
    }
  }

  .p-checkbox {
    width: 14px;
    height: 14px;
    outline: none;
    box-shadow: none;
    border: 1.5px solid #000000de;
    border-radius: 2px;
    cursor: pointer;

    .p-checkbox-box {
      width: 100%;
      height: 100%;
      outline: none;
      border: none;
      border-radius: 0px;
    }

    &:focus,
    &:hover {
      outline: none;
    }

    &.p-highlight {
      border: 1px solid #4263eb;
    }
  }
}`

**Pull request closed without merging**
