### PR TITLE
Fix: Calendar: showOtherMonths issue

### LINKED ISSUE #4099: Calendar: showOtherMonths - does not match the description in the documentation #2810
### Describe the bug
Documentation: (versions 2 and 3)
showOtherMonths [ boolean : true ] Whether to display dates in other months (non-selectable) at the start or end of the current month...

### Current lib code:
```
onPrevButtonClick(event) {
    if(this.showOtherMonths) {
        this.navigationState = {backward: true, button: true};
        this.navBackward(event);
    }
},
onNextButtonClick(event) {
    if(this.showOtherMonths) {
        this.navigationState = {backward: false, button: true};
        this.navForward(event);
    }
},
```

### Reproducer

https://codesandbox.io/s/funny-moon-i48yc4

### PrimeVue version

3.25.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

_No response_

### Steps to reproduce the behavior

add :showOtherMonths="false"

### Expected behavior

Dates in other months are invisible.
Prev/next month buttons are enabled.

### PR DESCRIPTION
**Pull request by amal-qb**
### Defect Fixes
Fixes #4099

### CODE REVIEW

**Comment by amal-qb** [comment]
@mertsincan Can you please review this PR?

**Comment by amal-qb** [comment]
@tugcekucukoglu Can you please review this PR?

**Comment by mertsincan** [comment]
Hi @amal-qb,

Thanks a lot for your contribution! But, this PR is outdated! Could you please update it? Then, I'll review it asap.

Sorry for the delayed response!
Best Regards,

**Comment by amal-qb** [comment]
This PR auto-closed when I synced the forked repository. I'll open another PR.

**Comment by amal-qb** [comment]
@mertsincan Updated on new PR: https://github.com/primefaces/primevue/pull/4385.

**Pull request closed without merging**
