### PR TITLE
Unable to set left margin of my choice in Treetable Toggler button(ex…

### PR DESCRIPTION
**Pull request by MohanYadav1**
Below is the raised defect of the same.

https://github.com/primefaces/primevue/issues/495

### CODE REVIEW

**Comment by MohanYadav1** [comment]
It is urgent for me. Please do the needful.

**Comment by cagataycivici** [comment]
Will merge manually

**Comment by MohanYadav1** [comment]
Thanks @cag can you please tell when you will merge today or tomorrow. And one thing more I have install .7 version do I need to update version to get latest fixed. Please tell me the step to get updated fixed in my project will it be by taking latest version like .9 or something else.

**Comment by MohanYadav1** [comment]
Any updates on this merge.

**Comment by MohanYadav1** [comment]
> Any updates on this merge.

@cagataycivici Can you please do this now as i need it.

**Comment by LadislavBohm** [comment]
@MohanYadav1 so use your forked version for the moment. Why do you make such a drama about this here, it's open source project.

**Comment by MohanYadav1** [comment]
> @MohanYadav1 so use your forked version for the moment. Why do you make such a drama about this here, it's open source project.

Sorry for that @LadislavBohm . I am new in github but as you suggested for a time being i am using my forked version but i will need to this forked code changes into Main Primevue branch so that all team members of mine will have same package instead of fork. I will keep my eye on it so that once it will in master then i will remove forked version reference from my project. Thanks

**Pull request closed without merging**
